# Heavily inspired by https://github.com/yyewolf/infra/blob/main/flux/infrastructure/cilium/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-api-crd/
  - envoy-gateway/
  - cilium/